on:
  push:
    branches: [ "main" ]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Run ci.sh
        run: chmod +x ci.sh && ./ci.sh

      - name: Log-in to ACR
        run: az acr login --name splitorstealcontainerregistry

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: splitorstealcontainerregistry.azurecr.io/server
